services:
  vite-app:
    build:
      context: .
      dockerfile: docker/vite-image/DockerFile
    volumes:
      - .:/app
      - nodemodules-project-volume:/app/node_modules
    environment:
      NODE_ENV: development
    restart: unless-stopped
    expose:
      - "5173"
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/DockerFile
    ports:
      - "5173:80"
    depends_on:
      - vite-app
    networks:
      - app-network

  postgres-service:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "6789:5432"
    volumes:
      - pgdata-project-volume:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      app-network:
        aliases:
          - postgres_host
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10

  api-node:
    build:
      context: .
      dockerfile: docker/api-node/DockerFile
    volumes:
      - .:/app
      - nodemodules-project-volume:/app/node_modules
    environment:
      DB_HOST: postgres_host
      DB_PORT: "5432"
      DB_USER: ${POSTGRES_USER}
      DB_PASS: ${POSTGRES_PASSWORD}
      DB_NAME: ${POSTGRES_DB}
      NODE_PORT: ${NODE_PORT}
    depends_on:
      postgres-service:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata-project-volume:
  nodemodules-project-volume:
