services:
  vite-app:
    build:
      context: .
      dockerfile: docker/vite-image/DockerFile
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    restart: unless-stopped
    expose:
      - "5173"
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: docker/nginx/DockerFile
    ports:
      - "5173:80"
    depends_on:
      - vite-app
    networks:
      - app-network

  postgres-service:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "6789:5432"
    volumes:
      - pgdata-project-volume:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    networks:
      app-network:
        aliases:
          - postgres_host

  api-node:
    build:
      context: .
      dockerfile: docker/api-node/DockerFile
    depends_on:
      - postgres-service
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  pgdata-project-volume:
  vite-node-modules: 
